
//! Autogenerated weights for `pallet_bullposting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-02-19, STEPS: `5`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `BeefSlab`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-bullposting-runtime/solochain_bullposting_runtime.compact.compressed.wasm
// --pallet
// pallet_bullposting
// --extrinsic
// *
// --steps
// 5
// --repeat
// 2
// --template
// ./pallets/benchmarking/frame-weight-template.hbs
// --output
// ./pallets/bullposting/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_bullposting`.
pub trait WeightInfo {
	fn try_submit_post(x: u32, ) -> Weight;
	fn try_submit_vote(x: u32, y: u32, ) -> Weight;
	fn try_update_vote(x: u32, y: u32, ) -> Weight;
	fn try_resolve_post(x: u32, ) -> Weight;
	fn try_unfreeze_vote(x: u32, y: u32, ) -> Weight;
}

/// Weights for `pallet_bullposting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	fn try_submit_post(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `164`
		//  Estimated: `3598`
		// Minimum execution time: 39_305_000 picoseconds.
		Weight::from_parts(50_924_000, 3598)
			// Standard Error: 4
			.saturating_add(Weight::from_parts(10, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	/// The range of component `y` is `[0, 20000000]`.
	fn try_submit_vote(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `4764`
		// Minimum execution time: 36_301_000 picoseconds.
		Weight::from_parts(53_890_657, 4764)
			// Standard Error: 3
			.saturating_add(Weight::from_parts(4, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	/// The range of component `y` is `[0, 20000000]`.
	fn try_update_vote(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `4764`
		// Minimum execution time: 41_605_000 picoseconds.
		Weight::from_parts(48_342_099, 4764)
			// Standard Error: 2
			.saturating_add(Weight::from_parts(6, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	fn try_resolve_post(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3598`
		// Minimum execution time: 50_546_000 picoseconds.
		Weight::from_parts(58_204_800, 3598)
			// Standard Error: 3
			.saturating_add(Weight::from_parts(6, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:0)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	/// The range of component `y` is `[0, 20000000]`.
	fn try_unfreeze_vote(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `4764`
		// Minimum execution time: 41_633_000 picoseconds.
		Weight::from_parts(42_979_457, 4764)
			// Standard Error: 1
			.saturating_add(Weight::from_parts(3, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	fn try_submit_post(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `164`
		//  Estimated: `3598`
		// Minimum execution time: 39_305_000 picoseconds.
		Weight::from_parts(50_924_000, 3598)
			// Standard Error: 4
			.saturating_add(Weight::from_parts(10, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	/// The range of component `y` is `[0, 20000000]`.
	fn try_submit_vote(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `4764`
		// Minimum execution time: 36_301_000 picoseconds.
		Weight::from_parts(53_890_657, 4764)
			// Standard Error: 3
			.saturating_add(Weight::from_parts(4, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	/// The range of component `y` is `[0, 20000000]`.
	fn try_update_vote(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `4764`
		// Minimum execution time: 41_605_000 picoseconds.
		Weight::from_parts(48_342_099, 4764)
			// Standard Error: 2
			.saturating_add(Weight::from_parts(6, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	fn try_resolve_post(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3598`
		// Minimum execution time: 50_546_000 picoseconds.
		Weight::from_parts(58_204_800, 3598)
			// Standard Error: 3
			.saturating_add(Weight::from_parts(6, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:0)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[0, 2000000]`.
	/// The range of component `y` is `[0, 20000000]`.
	fn try_unfreeze_vote(x: u32, _y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `4764`
		// Minimum execution time: 41_633_000 picoseconds.
		Weight::from_parts(42_979_457, 4764)
			// Standard Error: 1
			.saturating_add(Weight::from_parts(3, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
